# Copyright (c) 2025 Arduino SA
# SPDX-License-Identifier: Apache-2.0

# ST7701 panel display driver must initialize after the MIPI-DSI host.
CONFIG_DISPLAY_INIT_PRIORITY=87
CONFIG_STM32_LTDC_DISABLE_FMC_BANK1=y
